### ISSUE TITLE
Welcome Tour dialog won't appear on clean XP installation

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-admin-home#22]
@alansemenov commented on [Tue Mar 20 2018](https://github.com/enonic/lib-admin-ui/issues/409)

1. Make sure you have line ``tourDisabled = false`` in ``com.enonic.xp.admin.ui.cfg`` and it's not commented out
2. Run clean installation of XP 6.14.1
3. Click "or logged in without a user" link on the ID provider page

![image](https://user-images.githubusercontent.com/11612490/37660401-a206751a-2c52-11e8-986f-5801c82508b7.png)

On the Home dashboard the Welcome Tour dialog is supposed to automatically pop-up and the background is blurred as when the dialog is active, but the dialog itself is not visible. Happens only the first time, if you manually delete the browser cookie then the dialog will pop-up fine.

![image](https://user-images.githubusercontent.com/11612490/37660667-33b671ea-2c53-11e8-942a-9df5d0ec93cb.png)

**Comment by jsi** [comment]
I have just tested this with the latest snapshot of 6.15.0 and 6.14.2-B3, and the following happens:
`#tourDisabled = false`
-> Welcome tour appears, as it should
`tourDisabled = false`
-> No welcome tour (This is wrong)
`tourDisabled = true`
-> No welcome tour as it should.

**Comment by alansemenov** [comment]
``tourDisabled=false`` is not supported. The idea is that the tour is disabled by default but you can enable it by adding ``tourDisabled=true`` to the config. 

It's also described in the docs:

![image](https://user-images.githubusercontent.com/11612490/37964689-aab7c644-31c2-11e8-9097-93e5cb2e7975.png)

Plus, this bug was not about that setting at all, it was about that when the Tour dialog was supposed to auto-open it won't render properly.

**Comment by alansemenov** [comment]
Added support of ``tourDisabled=false`` to 6.15
