### ISSUE TITLE
Configuration issue - Xp Tour icon should not be present, when "tourDisabled = true"

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-admin-home#35]
1. Go to `home/config` folder
2. set `tourDisabled = true`    (com.enonic.xp.app.main.cfg)
Navigate to Home Page
**Bug:**   Xp Tour icon should not be present
![image](https://user-images.githubusercontent.com/3728712/42888505-187e7cf8-8ab1-11e8-8dc9-68a16141a5be.png)

**Comment by jsi** [comment]
This is a bug in version 6.15.0.  Must be verified on 7.0.0 after it is fixed.

**Comment by alansemenov** [comment]
@sgauruseu I can't reproduce this. For me the icon disappears when I paste this line into the config file.
