### ISSUE TITLE
Possibly invalid redirect on session expired

### ISSUE THREAD

**Issue by rymsha** [enonic/app-admin-home#516]
With the following vhost config
```
enabled = true

mapping.a.host = localhost
mapping.a.source = /
mapping.a.target = /admin
mapping.a.idProvider.system = default
```

Due to this code
https://github.com/enonic/app-admin-home/blob/master/src/main/resources/assets/js/home/main.ts#L86
when session expires `window.location.href = '//tool'` code gets called. That is same as calling `window.location.href = 'http://tool'`, but expected one is probably `window.location.href = '/tool'`

**Comment by alansemenov** [comment]
Fixed with recent changes
