### ISSUE TITLE
Launcher button takes focus!

### ISSUE THREAD

**Issue by ComLock** [enonic/app-admin-home#62]
I have a admin app in which I add the launcher so it looks professional.
Many of the admin app pages are react apps which contain a form with inputs.

After loading the page you click a input field and is going to start typing into that field.
However suddenly focus dissappears because the launcher panel has stolen it.

I believe this is the cause:
https://github.com/enonic/app-admin-home/blob/c2155a6777e82346c345223a5326ee08a3a864df/src/main/resources/assets/js/launcher/launcher.ts#L27

**Comment by ComLock** [comment]
The result is a feeling that the admin app is totally broken.

**Comment by ComLock** [comment]
This is still the case in lib-admin-7.0.2

**Comment by alansemenov** [comment]
Fixed in the upcoming release.
