### ISSUE TITLE
Translate missing language phrases to French

### ISSUE THREAD

**Issue by jsi** [enonic/app-admin-home#75]
The following keys are missing in 'phrases_fr.properties': 
 - home.dashboard.about.dialog.license.error
 - home.dashboard.about.dialog.license.name
 - home.dashboard.about.dialog.license.title

**Comment by GlennRicaud** [comment]
Two problems in the default properties file:
- "home.dashboard.about.dialog" without any value.
- The license name ("home.dashboard.about.dialog.license.name") is a proper noun, not a common noun. No need to translate
