### ISSUE TITLE
Admin tools menu not loaded if admin tool's xml has invalid chars

### ISSUE THREAD

**Issue by ashklianko** [enonic/app-admin-home#778]
Add chars from non-English alphabet to any admin tool's xml (e.g. studio plus), I used belarusian ones:
-admin tools menu stops loading
-errors spawn in the server console
That means that one invalid xml may break home app with dozens of admin tools

**Comment by alansemenov** [comment]
@ashklianko Please add a sample schema. I didn't manage to break it using cyrillic in display name, interface or config.

**Comment by ashklianko** [comment]
@alansemenov rechecked again, it was not an issue of the main app, issue is from XP. I've made studio plus's main.xml incorrect by adding some chars after closing </tool> tag and got errors on the backend and main launcher stopped loading, however broken widget's configs don't break anything
