### ISSUE TITLE
Change layout of the Launcher menu

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-admin-home#85]
* Replace burger icon with "XP" text

![image](https://user-images.githubusercontent.com/11612490/70613907-c85c5880-1c09-11ea-98f3-50a1ed4da1b0.png)

* In expanded mode "P" from "XP" should disappear leaving "X" to act like the close/collapse icon

![image](https://user-images.githubusercontent.com/11612490/70614257-79fb8980-1c0a-11ea-9aca-c898fb0c85a0.png)

* Use the same red color we are using for the left border to highlight the entire selected menu item with red background color

![image](https://user-images.githubusercontent.com/11612490/70614326-9992b200-1c0a-11ea-95bb-1e0c6f5d3cce.png)

**Comment by sigdestad** [comment]
Hm.. What happened to the red XP when active?

**Comment by ashklianko** [comment]
Will update
