### ISSUE TITLE
Unable to log out if name + username is lengthy

### ISSUE THREAD

**Issue by diegopasten** [enonic/app-admin-home#88]
On a ADFS system at a customer I was registerered with my full name including middle name.
With this and the username I recieved log out was impossible from admin window, in the lower right corner.

Example of how how long this string got in this case:
Diego Alonso Pasten uv-3penonicDAP@company.com [LOG OUT]

Maybe the log out button doesnt need to present both user and email. Or the this info should be in a separate divider/container

**Comment by alansemenov** [comment]
Couldn't reproduce, maybe it was fixed earlier

 ![image](https://user-images.githubusercontent.com/11612490/82034524-93fc3500-969e-11ea-9952-f6155cc53738.png)
